language: java

matrix:
  include:
    - os: linux
      jdk: openjdk8
      
# first, fix the issues with the dynamic libraries
#    - os: osx
#      osx_image: xcode9.3 # the latest image compatible with JDK8

python:
    - "2.7"

# required to compile z3
addons:
  apt:
    packages:
    - gcc-4.7
    - g++-4.7

cache:
  directories:
    - 3rdparty/z3
    - $HOME/.m2

# locally compile z3 and make it available via LD_LIBRARY_PATH
before_install:
    - pushd 3rdparty
    - ./install-local.sh
    - popd
    #- pip install release-me

#after_success:
#- sudo pip install --upgrade pip
#- sudo pip install --user release-me
#- ./script/release --overwrite latest-unstable ./script/latest-message.txt

script:
    - make integration

notifications:
    email:
      recipients:
        apalache-build@forsyte.at andrey@informal.systems
      on_success: change
      on_failure: always

