language: java

matrix:
  include:
    - os: linux
      jdk: openjdk8
# the build for osx still does not work, DYLD_LIBRARY_PATH does not solve the problem
#    - os: osx
#      osx_image: xcode8 # fixing the issue with oraclejdk8 on macos

python:
    - "2.7"

# required to compile z3
addons:
  apt:
    packages:
    - gcc-4.7
    - g++-4.7

cache:
  directories:
    - 3rdparty/z3
    - $HOME/.m2

# locally compile z3 and make it available via LD_LIBRARY_PATH
before_install:
    #- pip install release-me

    #after_success:
    #- sudo pip install --upgrade pip
    #- sudo pip install --user release-me
    #- ./script/release --overwrite latest-unstable ./script/latest-message.txt

branches:
  only:
  - master
  - unstable
  - types
  - feature/keramel

script:
    - make integration

notifications:
    email:
      recipients:
        apalache-build@forsyte.at andrey@informal.systems
      on_success: change
      on_failure: always

