language: java

jdk:
    - oraclejdk8

python:
    - "2.7"

os:
    - linux
    - osx

# required to compile z3
addons:
  apt:
    packages:
    - gcc-4.7
    - g++-4.7

cache:
  directories:
    - 3rdparty/z3
    - $HOME/.m2

# locally compile z3 and make it available via LD_LIBRARY_PATH
before_install:
  - pushd 3rdparty
  - ./install-local.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_LIBRARY_PATH=$JAVA_LIBRARY_PATH:"$PWD/lib"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$PWD/lib"; fi
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$PWD/lib"
  - popd

branches:
  only:
  - master
  - unstable

notifications:
    email:
      recipients:
        apalache-build@forsyte.at
      on_success: change
      on_failure: always

